version: '3'
services:
 mongodb:
   image: mongo
   ports:
     - "27017:27017"
   container_name: mongo2
   network_mode: host
 muzixapp:
   image: trackservice
   build: MuzixTasksUpdated/
   restart: always
   container_name: trackservice2
   network_mode: host
   ports:
     - "8090:8090"
   expose:
     - 8090
 zuul:
   image: zuul-service
   build: zuul-service/
   restart: always
   container_name: zuulservice2
   network_mode: host
   ports:
     - "8080:8080"
   expose:
     - 8080
 eureka:
   image: eureka-service
   build: eureka-service/
   restart: always
   container_name: eurekaservice2
   network_mode: host
   ports:
     - "8761:8761"
   expose:
     - 8761
 config:
   image: config-server
   build: configserver/
   restart: always
   container_name: configserver2
   network_mode: host
   ports:
     - "8888:8888"
   expose:
     - 8888

